version: 2.1

docker-image: &docker-image
  docker:
      - image: circleci/node:13.8.0
orbs:
  aws-cli: circleci/aws-cli@2.0.3
jobs:
  #  build:  # Choose any name, such as `build`
        # The primary container, where your job's commands will run
  #      <<: *docker-image
  #      steps:
  #        - checkout # check out the code in the project directory
  #        - run: echo "hello world" # run the `echo` command
#  create_infrastructure:
#    docker:
#      - image: amazon/aws-cli
#     steps:
#      - checkout
#      - run: 
#          name: "Create Cloudformation Stack"
#          command: |
#            aws cloudformation deploy \
#            --template-file template.yml \
#            --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
#            --region us-east-1

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["5a:1e:87:4a:07:bb:05:6b:7b:fb:b5:2b:0a:3e:a6:1e"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml

workflows:
    myWorkflow:
      jobs:
#        - create_infrastructure
        - configure_infrastructure
